---
matrix:
  include:
    - name: Markdown Linting
      stage: lint
      language: ruby
      rvm:
        - "2.7.1"
      install:
        - gem install mdl
        - echo -e "all\nrule 'MD013', :line_length => 120" > custom_rules.rb
      script:
        - mdl . --style custom_rules.rb
  
    - name: Javascript Linting
      stage: lint
      language: node_js
      node_js:
        - stable
      install:
        - npm install eslint --save-dev
      cache:
        directories:
          - node_modules
      script:
        - ./node_modules/.bin/eslint *.js

notifications:
  email: false
